---
abstract: 'Read individual characters from the keyboard using Win32::Console'
author:
  - 'Klaus Eichner <klaus03@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.141170'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Win32-Readch
no_index:
  directory:
    - t
    - inc
requires:
  Win32::Console: '0'
  Win32::IPC: '0'
resources:
  repository: https://github.com/klaus03/Win32-Readch.git
version: '0.03'
